modLoader="javafml"
loaderVersion="[1,)" 
license="MIT"

[[mods]]
modId="mlsg_ad_forge"
version="1.0"
displayName="MLSG - Client Ad"
displayURL="https://mlsg.mr-leaves.com"
logoFile= "../mlsg_ad_logo.png"
description='''
海外华人开服的第一选择！
专注海外市场！保姆级服务！
全球节点可选，模组包一键开服。
'''
authors="菜菜云MLSG"

[[dependencies.mlsg_ad_forge]]
    modId="forge"
    mandatory=true
    versionRange="[1,)"
    ordering="NONE"
    side="CLIENT"